"""AnalysisReport to HTML rendering."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import jinja2
import structlog
from markupsafe import Markup

from routebench.analysis.visuals.charts import (
    benchmark_gap_chart,
    capacity_utilization_chart,
    sequencing_index_distribution,
    time_distribution,
)
from routebench.analysis.visuals.maps import render_route_map
from routebench.core.findings import AnalysisReport
from routebench.report.prose_slots import ProseSlot, identify_prose_slots

logger: structlog.stdlib.BoundLogger = structlog.get_logger()

_TEMPLATES_DIR = Path(__file__).parent / "templates"
_STATIC_DIR = Path(__file__).parent / "static"


class ReportDocument:
    """Renders an AnalysisReport + prose into a standalone HTML file."""

    def __init__(self, analysis: AnalysisReport) -> None:
        self._analysis = analysis
        # autoescape is ON: the report interpolates strings taken verbatim from
        # the uploaded CSV (`route_id` above all), and it is served as text/html
        # by GET /sessions/{id}/report.html. With escaping off, a route_id of
        # `<script>...</script>` executed in the viewer's browser — stored XSS
        # against whoever opened a shared report.
        #
        # The two values that are genuinely markup — the stylesheet and the
        # chart SVGs — are wrapped in Markup at the call site rather than
        # trusted wholesale here. They are generated by this package; nothing
        # user-controlled reaches them as markup.
        self._env = jinja2.Environment(
            loader=jinja2.FileSystemLoader(str(_TEMPLATES_DIR)),
            autoescape=True,
            undefined=jinja2.Undefined,
        )

    def identify_prose_slots(self) -> list[ProseSlot]:
        """Identify which prose slots need to be filled."""
        return identify_prose_slots(self._analysis)

    def render(
        self,
        prose: dict[str, str],
        verification: dict[str, Any] | None = None,
    ) -> str:
        """Render the full report as a self-contained HTML string.

        Args:
            prose: Dict mapping slot_id to generated prose text.
            verification: Optional slot_id -> VerificationResult. Drives the
                footer, which reports each status separately so a deterministic
                fallback is never presented as a verified claim.

        Returns:
            Complete HTML document as a string.
        """
        css = Markup((_STATIC_DIR / "styles.css").read_text())

        # Build chart SVGs
        route_metrics_dict: dict[str, Any] = {
            rid: rm.model_dump() for rid, rm in self._analysis.route_metrics.items()
        }
        benchmark_dict: dict[str, Any] | None = (
            self._analysis.benchmark.model_dump() if self._analysis.benchmark else None
        )

        charts = {
            "time_distribution": Markup(time_distribution(route_metrics_dict)),
            "sequencing_index": Markup(sequencing_index_distribution(route_metrics_dict)),
            "capacity_utilization": Markup(capacity_utilization_chart(route_metrics_dict)),
            "benchmark_gap": Markup(benchmark_gap_chart(benchmark_dict)),
        }

        # Sort findings by severity for template
        severity_order = {
            "critical": 0,
            "high": 1,
            "medium": 2,
            "low": 3,
            "info": 4,
        }
        sorted_findings = sorted(
            self._analysis.findings,
            key=lambda f: severity_order.get(f.severity, 4),
        )

        # Build route maps for findings
        maps = self._build_finding_maps(sorted_findings)

        template = self._env.get_template("base.html.j2")
        html = template.render(
            fleet_metrics=self._analysis.fleet_metrics,
            route_metrics=self._analysis.route_metrics,
            findings=sorted_findings,
            benchmark=self._analysis.benchmark,
            grade=self._analysis.grade,
            prose=prose,
            charts=charts,
            maps=maps,
            analyses_run=self._analysis.analyses_run,
            analyses_skipped=self._analysis.analyses_skipped,
            metadata=self._analysis.metadata,
            verification=self._verification_summary(verification),
            css=css,
        )
        return html

    def _verification_summary(
        self,
        verification: dict[str, Any] | None,
    ) -> dict[str, Any] | None:
        """Shape verification results for the footer template."""
        if not verification:
            return None
        counts: dict[str, int] = {"verified": 0, "regenerated": 0, "fallback": 0}
        slots: list[dict[str, str]] = []
        for slot_id, result in sorted(verification.items()):
            status = getattr(result, "status", "verified")
            counts[status] = counts.get(status, 0) + 1
            slots.append({"slot_id": slot_id, "status": status})
        return {"counts": counts, "slots": slots, "total": len(slots)}

    def _build_finding_maps(
        self,
        findings: list[Any],
    ) -> dict[str, str]:
        """Render route maps for findings with route references."""
        maps: dict[str, str] = {}
        fleet = self._analysis.fleet
        route_map = {r.route_id: r for r in fleet.routes}

        for finding in findings:
            if finding.severity not in ("critical", "high", "medium"):
                continue
            for rid in finding.references.route_ids:
                route = route_map.get(rid)
                if route is None:
                    continue
                route_data: dict[str, Any] = {
                    "depot_lat": route.depot_lat,
                    "depot_lon": route.depot_lon,
                    "stops": [
                        {
                            "latitude": s.latitude,
                            "longitude": s.longitude,
                            "stop_sequence": s.stop_sequence,
                        }
                        for s in route.stops
                    ],
                }
                flagged = [
                    {"stop_sequence": seq}
                    for _rid, seq in finding.references.stop_sequences
                    if _rid == rid
                ]
                img = render_route_map(route_data, flagged or None)
                if img:
                    maps[finding.finding_id] = img
                    break  # one map per finding
        return maps
