"""Export the sample fleet's grade for the web app's score preview.

The landing page shows a scorecard before you upload anything, so users see the
payoff first. That scorecard must be a real grade of the committed sample fleet,
not invented numbers — so it is generated here and committed as JSON rather than
hand-written into the UI.

Runs without OSRM (stub matrix), which means the numbers are illustrative of the
SHAPE of a grade rather than a claim about a real fleet. The UI labels it as an
example. Regenerate whenever the rubric or the sample fleet changes:

    uv run python scripts/export_sample_grade.py
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

from routebench.analysis.scoring import compute_scorecard
from routebench.analysis.scoring.grading import compute_grade
from routebench.core.config import AnalysisConfig
from routebench.core.validation import validate_csv
from routebench.infra.matrix.base import MatrixResult

REPO_ROOT = Path(__file__).parent.parent
SAMPLE_CSV = REPO_ROOT / "data" / "samples" / "v1" / "sample_fleet.csv"
OUTPUT = REPO_ROOT / "web" / "src" / "lib" / "sample-grade.json"

# Uniform travel times: enough to grade the fleet's shape without OSRM. Matches
# tests/analysis/test_traffic.py's FlatProvider so the exported grade agrees
# with the snapshot test.
LEG_SECONDS = 600.0
LEG_METERS = 5000.0


class StubMatrixProvider:
    """Uniform matrix — no OSRM, no network."""

    name = "stub"

    def get_matrix(
        self,
        origins: list[tuple[float, float]],
        destinations: list[tuple[float, float]],
        departure_time: datetime | None = None,
        origin_departure_times: list[datetime] | None = None,
    ) -> MatrixResult:
        n_o, n_d = len(origins), len(destinations)
        return MatrixResult(
            durations_seconds=[[LEG_SECONDS] * n_d for _ in range(n_o)],
            distances_meters=[[LEG_METERS] * n_d for _ in range(n_o)],
            provider="stub",
            cached=False,
        )


def main() -> None:
    if not SAMPLE_CSV.exists():
        msg = f"Sample fleet not found: {SAMPLE_CSV}. Run scripts/generate_sample_fleet.py."
        raise SystemExit(msg)

    fleet, report = validate_csv(SAMPLE_CSV)
    if fleet is None:
        msg = f"Sample fleet failed validation: {[e.message for e in report.errors]}"
        raise SystemExit(msg)

    fleet_metrics, route_metrics = compute_scorecard(fleet, StubMatrixProvider(), AnalysisConfig())
    grade = compute_grade(fleet_metrics, route_metrics, findings=[], benchmark=None)

    payload = {
        "_comment": (
            "Generated by scripts/export_sample_grade.py from data/samples/v1/sample_fleet.csv. "
            "Illustrative: computed with a stub matrix, not live OSRM. Do not hand-edit."
        ),
        "grade": grade.model_dump(),
        "fleet": {
            "routes": fleet_metrics.total_routes,
            "stops": fleet_metrics.total_stops,
        },
    }

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(json.dumps(payload, indent=2) + "\n")
    overall = grade.overall
    print(f"Wrote {OUTPUT.relative_to(REPO_ROOT)}")
    print(f"  {fleet_metrics.total_routes} routes, {fleet_metrics.total_stops} stops")
    print(
        f"  overall: {overall.score:.1f} ({overall.letter}) under rubric v{grade.grading_version}"
    )


if __name__ == "__main__":
    main()
